### ISSUE TITLE
Development of PoA Based Ethereum Node Cluster for Development

### ISSUE THREAD

**Issue by Ansh-Sarkar** [Samagra-Development/competency_passbook#1]
Issue for aggregating PRs related to the development of the PoA based Private Ethereum Cluster.

**Comment by ChakshuGautam** [comment]
@Ansh-Sarkar We can discuss on how to detail this out here - https://github.com/Samagra-Development/vp/issues/2

**Comment by Ansh-Sarkar** [comment]
Yes sir. Sure.
